name: release-deploy
on:
  workflow_dispatch:
jobs:
  build_push_docker:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
