name: release-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_push_docker:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Get PR Number for Commit
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context.payload));
